# Generated by Django 5.0.3 on 2024-04-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="post_images/", verbose_name="Изображение"
            ),
        ),
    ]
