# Generated by Django 3.2.16 on 2024-04-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20240404_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сomment',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
