# Generated by Django 3.2.16 on 2024-04-05 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20240404_2126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сomment',
            options={'ordering': ('created_at',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='сomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='Пост'),
        ),
        migrations.AlterField(
            model_name='сomment',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
